# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190119_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
